# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/data/home/charleshan/Lab2_2020/CompNet-Lab2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/data/home/charleshan/Lab2_2020/CompNet-Lab2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/home/charleshan/Lab2_2020/CompNet-Lab2/CMakeFiles /media/data/home/charleshan/Lab2_2020/CompNet-Lab2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/home/charleshan/Lab2_2020/CompNet-Lab2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named protocol_stack

# Build rule for target.
protocol_stack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protocol_stack
.PHONY : protocol_stack

# fast build rule for target.
protocol_stack/fast:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/build
.PHONY : protocol_stack/fast

#=============================================================================
# Target rules for targets named ip_tests2

# Build rule for target.
ip_tests2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ip_tests2
.PHONY : ip_tests2

# fast build rule for target.
ip_tests2/fast:
	$(MAKE) -f test_scripts/CMakeFiles/ip_tests2.dir/build.make test_scripts/CMakeFiles/ip_tests2.dir/build
.PHONY : ip_tests2/fast

#=============================================================================
# Target rules for targets named echo_server_multi

# Build rule for target.
echo_server_multi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server_multi
.PHONY : echo_server_multi

# fast build rule for target.
echo_server_multi/fast:
	$(MAKE) -f test_scripts/CMakeFiles/echo_server_multi.dir/build.make test_scripts/CMakeFiles/echo_server_multi.dir/build
.PHONY : echo_server_multi/fast

#=============================================================================
# Target rules for targets named echo_client

# Build rule for target.
echo_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_client
.PHONY : echo_client

# fast build rule for target.
echo_client/fast:
	$(MAKE) -f test_scripts/CMakeFiles/echo_client.dir/build.make test_scripts/CMakeFiles/echo_client.dir/build
.PHONY : echo_client/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f test_scripts/CMakeFiles/echo_server.dir/build.make test_scripts/CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named eth_tests

# Build rule for target.
eth_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eth_tests
.PHONY : eth_tests

# fast build rule for target.
eth_tests/fast:
	$(MAKE) -f test_scripts/CMakeFiles/eth_tests.dir/build.make test_scripts/CMakeFiles/eth_tests.dir/build
.PHONY : eth_tests/fast

#=============================================================================
# Target rules for targets named eth_tests2

# Build rule for target.
eth_tests2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eth_tests2
.PHONY : eth_tests2

# fast build rule for target.
eth_tests2/fast:
	$(MAKE) -f test_scripts/CMakeFiles/eth_tests2.dir/build.make test_scripts/CMakeFiles/eth_tests2.dir/build
.PHONY : eth_tests2/fast

#=============================================================================
# Target rules for targets named ip_tests

# Build rule for target.
ip_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ip_tests
.PHONY : ip_tests

# fast build rule for target.
ip_tests/fast:
	$(MAKE) -f test_scripts/CMakeFiles/ip_tests.dir/build.make test_scripts/CMakeFiles/ip_tests.dir/build
.PHONY : ip_tests/fast

src/BOBHash.o: src/BOBHash.cc.o

.PHONY : src/BOBHash.o

# target to build an object file
src/BOBHash.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/BOBHash.cc.o
.PHONY : src/BOBHash.cc.o

src/BOBHash.i: src/BOBHash.cc.i

.PHONY : src/BOBHash.i

# target to preprocess a source file
src/BOBHash.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/BOBHash.cc.i
.PHONY : src/BOBHash.cc.i

src/BOBHash.s: src/BOBHash.cc.s

.PHONY : src/BOBHash.s

# target to generate assembly for a file
src/BOBHash.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/BOBHash.cc.s
.PHONY : src/BOBHash.cc.s

src/arp.o: src/arp.cc.o

.PHONY : src/arp.o

# target to build an object file
src/arp.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/arp.cc.o
.PHONY : src/arp.cc.o

src/arp.i: src/arp.cc.i

.PHONY : src/arp.i

# target to preprocess a source file
src/arp.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/arp.cc.i
.PHONY : src/arp.cc.i

src/arp.s: src/arp.cc.s

.PHONY : src/arp.s

# target to generate assembly for a file
src/arp.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/arp.cc.s
.PHONY : src/arp.cc.s

src/common.o: src/common.cc.o

.PHONY : src/common.o

# target to build an object file
src/common.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/common.cc.o
.PHONY : src/common.cc.o

src/common.i: src/common.cc.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/common.cc.i
.PHONY : src/common.cc.i

src/common.s: src/common.cc.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/common.cc.s
.PHONY : src/common.cc.s

src/device.o: src/device.cc.o

.PHONY : src/device.o

# target to build an object file
src/device.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/device.cc.o
.PHONY : src/device.cc.o

src/device.i: src/device.cc.i

.PHONY : src/device.i

# target to preprocess a source file
src/device.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/device.cc.i
.PHONY : src/device.cc.i

src/device.s: src/device.cc.s

.PHONY : src/device.s

# target to generate assembly for a file
src/device.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/device.cc.s
.PHONY : src/device.cc.s

src/ip.o: src/ip.cc.o

.PHONY : src/ip.o

# target to build an object file
src/ip.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/ip.cc.o
.PHONY : src/ip.cc.o

src/ip.i: src/ip.cc.i

.PHONY : src/ip.i

# target to preprocess a source file
src/ip.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/ip.cc.i
.PHONY : src/ip.cc.i

src/ip.s: src/ip.cc.s

.PHONY : src/ip.s

# target to generate assembly for a file
src/ip.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/ip.cc.s
.PHONY : src/ip.cc.s

src/kernel.o: src/kernel.cc.o

.PHONY : src/kernel.o

# target to build an object file
src/kernel.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/kernel.cc.o
.PHONY : src/kernel.cc.o

src/kernel.i: src/kernel.cc.i

.PHONY : src/kernel.i

# target to preprocess a source file
src/kernel.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/kernel.cc.i
.PHONY : src/kernel.cc.i

src/kernel.s: src/kernel.cc.s

.PHONY : src/kernel.s

# target to generate assembly for a file
src/kernel.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/kernel.cc.s
.PHONY : src/kernel.cc.s

src/packetio.o: src/packetio.cc.o

.PHONY : src/packetio.o

# target to build an object file
src/packetio.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/packetio.cc.o
.PHONY : src/packetio.cc.o

src/packetio.i: src/packetio.cc.i

.PHONY : src/packetio.i

# target to preprocess a source file
src/packetio.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/packetio.cc.i
.PHONY : src/packetio.cc.i

src/packetio.s: src/packetio.cc.s

.PHONY : src/packetio.s

# target to generate assembly for a file
src/packetio.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/packetio.cc.s
.PHONY : src/packetio.cc.s

src/socket.o: src/socket.cc.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/socket.cc.o
.PHONY : src/socket.cc.o

src/socket.i: src/socket.cc.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/socket.cc.i
.PHONY : src/socket.cc.i

src/socket.s: src/socket.cc.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/socket.cc.s
.PHONY : src/socket.cc.s

src/tcp.o: src/tcp.cc.o

.PHONY : src/tcp.o

# target to build an object file
src/tcp.cc.o:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/tcp.cc.o
.PHONY : src/tcp.cc.o

src/tcp.i: src/tcp.cc.i

.PHONY : src/tcp.i

# target to preprocess a source file
src/tcp.cc.i:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/tcp.cc.i
.PHONY : src/tcp.cc.i

src/tcp.s: src/tcp.cc.s

.PHONY : src/tcp.s

# target to generate assembly for a file
src/tcp.cc.s:
	$(MAKE) -f CMakeFiles/protocol_stack.dir/build.make CMakeFiles/protocol_stack.dir/src/tcp.cc.s
.PHONY : src/tcp.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... protocol_stack"
	@echo "... edit_cache"
	@echo "... ip_tests2"
	@echo "... echo_server_multi"
	@echo "... echo_client"
	@echo "... echo_server"
	@echo "... eth_tests"
	@echo "... eth_tests2"
	@echo "... ip_tests"
	@echo "... src/BOBHash.o"
	@echo "... src/BOBHash.i"
	@echo "... src/BOBHash.s"
	@echo "... src/arp.o"
	@echo "... src/arp.i"
	@echo "... src/arp.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/device.o"
	@echo "... src/device.i"
	@echo "... src/device.s"
	@echo "... src/ip.o"
	@echo "... src/ip.i"
	@echo "... src/ip.s"
	@echo "... src/kernel.o"
	@echo "... src/kernel.i"
	@echo "... src/kernel.s"
	@echo "... src/packetio.o"
	@echo "... src/packetio.i"
	@echo "... src/packetio.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/tcp.o"
	@echo "... src/tcp.i"
	@echo "... src/tcp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

